name: Test DD Out

on:
  workflow_call:
    inputs:
      tfkey:
        description: 'AWS resource key'
        required: true
        type: string
      tfdir:
        description: 'AWS resource dir'
        required: true
        type: string
      use_domain:
        description: 'Set TF_VAR_fq_domain=main'
        type: number
        default: 0
  
jobs:
  job5:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        run: |
          echo "tfkey=${{ inputs.tfkey }}"
          echo "tfdir=${{ inputs.tfdir }}"
          echo "use_domain=${{ inputs.use_domain }}"
