name: Test DD Out

on:
  workflow_call:
    inputs:
      engine:
        description: 'AWS resource group to use'
        required: true
        type: string

jobs:
  job5:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        run: |
          echo "Data was: ${{inputs.engine}}"
