name: Test DD Out

on:
  workflow_call:
    inputs:
      resource:
        description: 'AWS resource group to use'
        required: true
        type: string
        
env:
  DATA: >
    {
      "AAA": { "key": "xyz" },
      "BBB": { "key": "123" },
      "CCC": { "key": "###" }
    }
  
jobs:
  job5:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        run: |
          echo ${{ inputs.resource }}
          echo ${{ fromJSON(env.DATA)[inputs.resource]['key'] }}
