name: Test DD

on:
  workflow_dispatch:
    inputs:
      resource:
        description: 'Data'
        required: false
        type: choice
        options:
        - AAA
        - BBB
        - CCC

env:
  RESOURCES: >
    {
      "AAA": {
        "key": "aaa-key",
        "dir": "fq/aaa-dir",
        "use_domain": "true"
      },
      "BBB": {
        "key": "bbb-key",
        "dir": "fq/bbb-dir"
      },
      "CCC": {
        "key": "ccc-key",
        "dir": "fq/ccc-dir",
        "use_domain": "true"
      },
    }
    
jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      tfkey: ${{ steps.setup.outputs.tfkey }}
      tfdir: ${{ steps.setup.outputs.tfdir }}
      use_domain: ${{ steps.setup.outputs.use_domain }}
    steps:
      - name: Setup resource values
        id: setup
        shell: bash
        run: |
          tfkey="${{ fromJson(env.RESOURCES)[inputs.resource]['key'] }}"
          echo "tfkey=$tfkey" >> $GITHUB_OUTPUT
          tfdir="${{ fromJson(env.RESOURCES)[inputs.resource]['dir'] }}"
          echo "tfdir=$tfdir" >> $GITHUB_OUTPUT
          use_domain="${{ fromJson(env.RESOURCES)[inputs.resource]['use_domain'] }}"
          echo "use_domain=$use_domain" >> $GITHUB_OUTPUT
  Process:
    needs: [Setup]
    uses: stpride/test1/.github/workflows/dd-out.yaml@main
    with:
      tfkey: ${{ needs.Setup.outputs.tfkey }}
      tfdir: ${{ needs.Setup.outputs.tfdir }}
      use_domain: ${{ needs.Setup.outputs.use_domain }}
