name: Test DD

on:
  workflow_dispatch:
    inputs:
      resource:
        description: 'Data'
        required: false
        type: choice
        options:
        - AAA
        - BBB
        - CCC

env:
  RESOURCES: >
    {
      "AAA": {
        "key": "aaa-key",
        "dir": "fq/aaa-dir",
        "use_domain": 0
      },
      "BBB": {
        "key": "bbb-key",
        "dir": "fq/bbb-dir"
      },
      "CCC": {
        "key": "ccc-key",
        "dir": "fq/ccc-dir",
        "use_domain": 0
      },
    }
    
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup resource values
        shell: bash
        run: |
          key="${{ fromJson(env.RESOURCE)[inputs.resource]['key'] }}"
          echo $key
          
  #test:
  #  uses: stpride/test1/.github/workflows/dd-out.yaml@main
  #  with:
  #    resource: ${{ inputs.data }}
