name: Test DD

on:
  workflow_dispatch:
    inputs:
      resource:
        description: 'Resource'
        required: false
        type: choice
        options:
        - AAA
        - BBB
        - CCC

env:
  ENGINE: >
    ${{ fromJson('{
      "AAA": "analytics",
      "BBB": "calculations",
      "CCC": "data"
    }')[github.event.inputs.resource] }}
    
jobs:
  test:
    uses: stpride/test1/.github/workflows/dd-out.yaml@main
    with:
      resource: .env.$ENGINE
