name: Test DD

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Data'
        required: false
        type: choice
        options:
        - AAA
        - BBB
        - CCC

jobs:
  test:
    uses: stpride/test1/.github/workflows/dd-out.yaml@main
    with:
      resource: >
        ${{ fromJson('{
          "AAA": {
            "tfkey": "analytics",
            "tfdir": "fq/analytics"
          },
          "BBB": {
            "tfkey": "calculations",
            "tfdir": "fq/calculations"
          },
          "CCC": {
            "tfkey": "goofy",
            "tfdir": "fq/goofy"
          },
        }')[github.event.inputs.data] }}
