name: 'Environment output'

on: [workflow_dispatch]

inputs:
  environment:
    description: 'Environment name to look up'
    required: false

#outputs:
#  environment:
#    value: ${{ steps.export.outputs.environment }}
#  account_number:
#    value: ${{ steps.export.outputs.account_number }}

jobs:
  test1:
    name: 'Test1'
    runs-on: ubuntu-latest

    steps:          
      - name: Get data
        uses: kanga333/variable-mapper@master
        with:
          key: "endsWith(${{github.ref}})"
          id : export
          shell: bash
          map: |
            {
              "one": {
                "environment": "aaa",
                "account_number": "1000"
              },
              "two": {
                "environment": "bbb",
                "account_number": "9999"
              }
            }
          export_to: env,log,output 
        
      - name: Echo environment and output
        shell: bash
        run: |
          echo ${{ steps.export.outputs.environment }}
          echo ${{ steps.export.outputs.account_number }} 
