name: Shared

on:
  workflow_call:
    inputs:
      count:
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  shared:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        run: echo "hello"
