name: Shared

on:
  workflow_call:
    inputs:
      count:
        type: boolean
        required: true
        default: true

defaults:
  run:
    shell: bash

jobs:
  shared:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        run: echo ${{ inputs.count }}
        
      - name: IfTrue
        if: inputs.count == true
        run: echo "TRUE"
        
      - name: IfFalse
        if: inputs.count == false
        run: echo "FALSE"
