name: Shared

on:
  workflow_call:
    inputs:
      count:
        type: string
        default: '2'

defaults:
  run:
    shell: bash

jobs:
  shared:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        run: |
          aaa=$((${{ inputs.count }}))
          echo $aaa
