name: Shared

on:
  workflow_call:
    inputs:
      count:
        type: string
        default: '2'

defaults:
  run:
    shell: bash

jobs:
  shared:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        run: |
          aaa=$((${{ inputs.count }}))
          echo $aaa
          if [ "${{ inputs.count }}" != "0" -a $aaa -eq 0 ]; then
            echo "Error: invalid input"
            exit 1
          fi
