name: Test-Cache

on: [workflow_dispatch]

defaults:
  run:
    shell: bash
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36
        with:
          terraform_wrapper: false
          terraform_version: '1.3.9'

      - name: Configure Terraform plugin cache
        run: |
          echo 'plugin_cache_dir = "$HOME/terraform-cach/.terraform.d/plugin-cache"' > ~/terraform-cach/.terraformrc
          mkdir -p ~/terraform-cach/.terraform.d/plugin-cache
          
      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: ~/terraform-cach/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles(format('{0}/.terraform.lock.hcl', ~/terraform-cach)) }}
          restore-keys: ${{ runner.os }}-terraform-

      - name: TF Init
        working-directory: ~/terraform-cach
        run: |
          terraform init
      
