name: Test Matrix

on:
  workflow_dispatch:
    
jobs:
  Preamble:
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.setup.outputs.result }}
    steps:
      - name: Setup environments
        uses: actions/github-script@v6
        id: setup
        with:
          script: |
            const environments = [];
            environments.push({
              "environment": "fq6",
              "aws-region": "us-west-2",
              "account-number": "300120355739"
            });
            return environments;
      
  MonorepoLambdas:
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.setup.outputs.result }}
    steps:
      - name: Run action
        id: setup
        uses: actions/github-script@v6
        with:
          script: |
            const lambdas = [];
            lambdas.push({
              "name": "enigma_machine",
              "dir": ".",
              "monorepo": false
            });
            return lambdas;

  TerraformPreprocess:
    needs: [Preamble, MonorepoLambdas]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deploy-environment: ${{ fromJson(needs.Preamble.outputs.data) }}
        lambdas: ${{ fromJson(needs.MonorepoLambdas.outputs.data) }}
    permissions:
      actions: read
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: Step1
        shell: bash
        run: |
          echo "environment: ${{ matrix.deploy-environment.environment }}"
          echo "aws-region: ${{ matrix.deploy-environment.aws-region }}"
          echo "account-number: ${{ matrix.deploy-environment.account-number }}"
          echo "lambda: ${{ matrix.lambdas.name }}"
          echo "dir: ${{ matrix.lambdas.dir }}"
          echo "monorepo: ${{ matrix.lambdas.monorepo }}"
  
      
