name: Test Action

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Run action
        id: get-lambdas
        uses: stpride/.github/.github/actions/monorepo@main

      - name: See lambdas
        shell: bash
        run: |
          echo ${{ steps.get-lambdas.output.lambdas }}
