name: Test-Cache

on: [workflow_dispatch]

defaults:
  run:
    shell: bash

env:
  TF_DIR: ${{ github.workspace }}/terraform-cach
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/terraform-cach/.terraform.d/plugin-cache
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36
        with:
          terraform_wrapper: false
          terraform_version: '1.3.9'

      - name: Configure Terraform plugin cache
        run: |
          echo 'plugin_cache_dir = "${{ env.TF_PLUGIN_CACHE_DIR }}"' > ${{ env.TF_DIR }}/.terraformrc
          mkdir -p ${{ env.TF_PLUGIN_CACHE_DIR }}
          
      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles(format('{0}/.terraform.lock.hcl', env.TF_DIR)) }}
          restore-keys: ${{ runner.os }}-terraform-

      - name: TF Init
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform init
      
